- name: Zephyr role handlers

  become: true
  become_user: "{{ zephyr_user }}"
  block:

  - name: Zephyr west update
    listen: west_update
    shell: |
      set -o errexit
      source ~/zephyrproject/.venv/bin/activate
      [[ -d ~/zephyrproject/.west ]] || west init -l ~/zephyrproject/zephyr/
      cd ~/zephyrproject
      west update
      west zephyr-export
    args:
      executable: /bin/bash

  - name: Zephyr venv shortcut
    listen: west_update
    file:
      src: "/home/{{ zephyr_user }}/zephyrproject/.venv/bin/activate"
      dest: "/home/{{ zephyr_user }}/zephyr_venv_activate"
      state: link

  - name: Zephyr unpack minimal SDK
    listen: zephyr_sdk_update
    unarchive:
      remote_src: yes
      list_files: yes
      src: "/home/{{ zephyr_user }}/{{ zephyr_sdk_file }}"
      dest: "/home/{{ zephyr_user }}"
    register: zephyr_sdk_unpack_files

  - name: Zephyr SDK registration helper for other users
    listen: zephyr_sdk_update
    template:
      src: zephyr_sdk_setup.sh.j2
      dest: /home/{{ zephyr_user }}/zephyr_sdk_setup.sh
      mode: '0755'

  - name: Zephyr setup SDK
    listen: zephyr_sdk_update
    command:
      argv:
        - /home/{{ zephyr_user }}/zephyr_sdk_setup.sh
        - -t arm-zephyr-eabi
        - -t x86_64-zephyr-elf
